name: Sync YouTube Playlist
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-list:
    runs-on: ubuntu-latest
    permissions: # Añadimos esto para asegurar el permiso de escritura
      contents: write
    steps:
      - uses: actions/checkout@v4 # Actualizado a v4
      - name: Set up Python
        uses: actions/setup-python@v5 # Actualizado a v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install google-api-python-client python-dotenv
      - name: Run script
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          PLAYLIST_ID: ${{ secrets.PLAYLIST_ID }}
        run: python sync_playlist.py
      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # Agregamos toda la carpeta de Playlists
          git add Mis_Playlists/*.txt
          git commit -m "Sync playlists folders" || exit 0
          git push
